name: GitHub To Trello Cards

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: "${{ secrets.GITHUB_SHA }}"
      - name: Install Dependencies
        run: cd ./.github/actions/trello_card && npm ci
      - uses: ./.github/actions/trello_card
        continue-on-error: false
        with:
          trello-api-key: ${{ secrets.TRELLO_KEY }}
          trello-auth-token: ${{ secrets.TRELLO_TOKEN }}
          trello-board-id: "6526e7251771fcc381a15e7b"
          trello-card-action: "Attachment"
          trello-list-name-commit: "Doing"
          trello-list-name-pr-open: "Review"
          trello-list-name-pr-closed: "Done"
          trello-card-id-pattern: "/\[t[:-](\w+)]/"
